window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.browserLang=(window.navigator.userLanguage||window.navigator.language).toUpperCase().slice(0,2);window.tildaBrowserLang=window.browserLang;function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t830_init(recid){var rec=document.getElementById('rec'+recid);var allRec=document.getElementById('allrecords');if(!allRec||!rec)return;var panel=rec.querySelector('.t830__panel');var overlay=rec.querySelector('.t830m__overlay');var menu=rec.querySelector('.t830m');var submenu=rec.querySelector('.t830m__submenu');var burger=rec.querySelector('.t830__side .t830__burger');var menuItemList=rec.querySelectorAll('.t830m__list-title a');var submenuItemList=rec.querySelectorAll('.t830m__submenu-item a');t830_initMenu(rec,menu,burger,overlay);t830_removePadding(rec,allRec);t830_calcCol(rec,menu,allRec,!1);t_onFuncLoad('t_menu__highlightActiveLinks',function(){t_menu__highlightActiveLinks('.t830m__list a')});t830_openSubmenu(rec);t830_hoverShowMenu(rec,menu,panel,overlay,burger);window.addEventListener('resize',function(){t830_calcCol(rec,menu,allRec,!0);t830_removePadding(rec,allRec);if(menu&&menu.classList.contains('t830m_close')&&window.innerWidth>1499){if(overlay)overlay.classList.remove('t830m__menu_show')}});if(submenu&&submenu.classList.contains('t830m__submenu_close')){t830_toggleMenu(rec)}
if(window.innerWidth>1199){t830_scrollSideMenu(rec)}
var isHashNotEmpty=window.location.hash.length!==0;Array.prototype.forEach.call(menuItemList,function(menuItem){menuItem.addEventListener('click',function(){if(isHashNotEmpty){Array.prototype.forEach.call(menuItemList,function(menuEl){menuEl.classList.remove('t-active')});menuItem.classList.add('t-active')}})});Array.prototype.forEach.call(submenuItemList,function(submenuItem){submenuItem.addEventListener('click',function(){if(isHashNotEmpty){Array.prototype.forEach.call(submenuItemList,function(submenuEl){submenuEl.classList.remove('t-active')});submenuItem.classList.add('t-active')}})});t_onFuncLoad('t_menu__findAnchorLinks',function(){t_menu__findAnchorLinks(recid,'.t830m__list a')})}
function t830_calcCol(rec,menu,allrecords,isResized){if(window.innerWidth<=1199||!menu||window.getComputedStyle(rec).display==='none')return;var label=document.querySelector('.t-tildalabel');if(menu.classList.contains('t830m_open')){if(allrecords)allrecords.classList.add('t830__allrecords_padd-small');if(label)label.classList.add('t830__t-tildalabel_padd-small')}else{if(allrecords)allrecords.classList.add('t830__allrecords_padd');if(label)label.classList.add('t830__t-tildalabel_padd')}
if(isResized)return;var event=document.createEvent('Event');event.initEvent('allRecPaddingInit',!0,!0);if(allrecords)allrecords.dispatchEvent(event)}
function t830_toggleMenu(rec){var titleList=rec.querySelectorAll('.t830m__list-title_toggle');Array.prototype.forEach.call(titleList,function(listTitle){listTitle.addEventListener('click',function(){var submenu=listTitle.nextElementSibling;var textTitle=listTitle.querySelector('.t830m__list-title-text');t830_slideToggle(submenu);if(textTitle)textTitle.classList.toggle('t830m__list-title-text_opacity');if(textTitle)textTitle.classList.toggle('t-menu__link-item')})})}
function t830_openSubmenu(rec){var activeLink=rec.querySelector('.t830m__submenu-item a.t-active');var submenu=activeLink?activeLink.closest('.t830m__submenu'):null;if(submenu)submenu.style.display='block'}
function t830_hoverShowMenu(rec,menu,panel,overlay,burger){if(window.innerWidth<=1199||!panel||!panel.classList.contains('t830__panel_hover'))return;panel.addEventListener('mouseenter',function(){if(menu)menu.classList.add('t830m__menu_show');if(burger)burger.classList.add('t830__burger_open');if(overlay)overlay.classList.add('t830m__overlay_hover')});if(menu){menu.addEventListener('mouseleave',function(){menu.classList.remove('t830m__menu_show');if(burger)burger.classList.remove('t830__burger_open')})}
if(overlay){overlay.addEventListener('mouseenter',function(){overlay.classList.remove('t830m__overlay_hover');if(burger)burger.classList.remove('t830__burger_open');if(menu)menu.classList.remove('t830m__menu_show')})}
var menuLinks=menu.querySelectorAll('a');Array.prototype.forEach.call(menuLinks,function(link){link.addEventListener('click',function(){menu.classList.remove('t830m__menu_show');if(burger)burger.classList.remove('t830__burger_open')})});if(burger){burger.addEventListener('click',function(){if(burger.classList.contains('t830__burger_open')){t830_closeMenu(rec,menu,overlay);burger.classList.remove('t830__burger_open')}else{burger.classList.add('t830__burger_open');if(menu)menu.classList.add('t830m__menu_show');if(overlay)overlay.classList.add('t830m__overlay_hover')}})}}
function t830_showMenu(rec,menu,burger,overlay){var panel=rec.querySelector('.t830__panel');document.body.classList.add('t830__body_menushowed');if(overlay)overlay.classList.add('t830m__menu_show');if(menu)menu.classList.add('t830m__menu_show');var closedMenuEls=rec.querySelectorAll('.t830m__overlay, .t830m__close, a[href*="#"]');closedMenuEls=Array.prototype.filter.call(closedMenuEls,function(el){return!(el.classList.contains('tooltipstered')||el.classList.contains('t794__tm-link')||el.classList.contains('t978__tm-link')||el.classList.contains('t966__tm-link'))});closedMenuEls.forEach(function(el){el.addEventListener('click',function(){t830_closeMenu(rec,menu,overlay);if(burger)burger.classList.remove('t830__burger_open')})});if(panel)panel.classList.add('t830__panel_close');var popupBg=document.querySelector('.t-site-search-popup__background');document.addEventListener('keydown',function(e){if(e.keyCode!==27||popupBg)return;document.body.classList.remove('t830__body_menushowed');if(menu)menu.classList.remove('t830m__menu_show');if(burger)burger.classList.remove('t830__burger_open');if(overlay)overlay.classList.remove('t830m__menu_show')})}
function t830_closeMenu(rec,menu,overlay){var panel=rec.querySelector('.t830__panel');if(menu&&menu.classList.contains('t830m_open')&&window.innerWidth<1500){if(panel)panel.classList.remove('t830__panel_close')}
document.body.classList.remove('t830__body_menushowed');if(menu)menu.classList.remove('t830m__menu_show');if(overlay)overlay.classList.remove('t830m__menu_show')}
function t830_initMenu(rec,menu,burger,overlay){if(!rec)return;var panel=rec.querySelector('.t830__panel');var menuContent=rec.querySelector('.t830__menu__content');if(typeof jQuery!=='undefined'){$('.t830').bind('clickedAnchorInTooltipMenu',function(){t830_closeMenu(rec,menu,overlay)})}else{var menuBlock=document.querySelector('.t830');if(menuBlock){menuBlock.addEventListener('clickedAnchorInTooltipMenu',function(){t830_closeMenu(rec,menu,overlay)})}}
if(!panel||!menuContent||!menu)return;if(panel.classList.contains('t830__panel_click')||(panel.classList.contains('t830__panel_hover')&&window.innerWidth<=1199)){menuContent.addEventListener('click',function(e){if(menu.classList.contains('t830m__menu_show')){if(burger)burger.classList.remove('t830__burger_open');t830_closeMenu(rec,menu,overlay)}else{if(burger)burger.classList.add('t830__burger_open');t830_showMenu(rec,menu,burger,overlay)}})}}
function t830_scrollSideMenu(rec){var container=rec?rec.querySelector('.t830m__container'):null;if(!container)return;var events=['scroll','wheel','DOMMouseScroll','mousewheel'];events.forEach(function(event){container.addEventListener(event,function(e){var searchResult=rec.querySelector('.t-site-search-dm');if(!searchResult){t830_stopScroll(container,e)}})})}
function t830_stopScroll(container,eventScroll){var scrollTop=container.scrollTop;var scrollHeight=container.scrollHeight;var height=container.offsetHeight;var delta=eventScroll.type==='DOMMouseScroll'?eventScroll.detail*-40:eventScroll.wheelDelta;var up=delta>0;var prevent=function(){eventScroll.stopPropagation();eventScroll.preventDefault();eventScroll.returnValue=!1;return!1};if(!up&&-delta>scrollHeight-height-scrollTop){container.scrollTo(0,scrollHeight);return prevent()}else if(up&&delta>scrollTop){container.scrollTo(0,0);return prevent()}}
function t830_removePadding(rec,allrecords){if(!allrecords||!rec||window.getComputedStyle(rec).display!=='none')return;allrecords.style.paddingLeft='0';var label=document.querySelector('.t-tildalabel');if(label)label.style.paddingLeft='0'}
function t830_slideToggle(target){if(!target)return;if(target.getAttribute('data-slide')==='y')return;if(window.getComputedStyle(target).display==='none'){return t830_slideDown(target)}else{return t830_slideUp(target)}}
function t830_slideUp(target){if(!target)return;var step=target.offsetHeight/30;var difference=target.offsetHeight;target.style.overflow='hidden';target.setAttribute('data-slide','y');var timerID=setInterval(function(){difference-=step;target.style.height=difference+'px';if(difference<=0){target.style.height='';target.style.overflow='';target.style.display='none';target.removeAttribute('data-slide');clearInterval(timerID)}},10)}
function t830_slideDown(target){if(!target)return;target.style.display='';var currentDisplayValue=window.getComputedStyle(target).display;target.style.display=currentDisplayValue==='none'?'block':currentDisplayValue;var targetHeight=target.offsetHeight;target.style.height='0';target.style.overflow='hidden';target.setAttribute('data-slide','y');var step=targetHeight/30;var difference=0;var timerID=setInterval(function(){target.style.height=difference+'px';difference+=step;if(difference>=targetHeight){target.style.height='';target.style.overflow='';target.removeAttribute('data-slide');clearInterval(timerID)}},10)}
function t754__init(recid){setTimeout(function(){t_onFuncLoad('t_prod__init',function(){t_prod__init(recid)});t754__hoverZoom_init(recid);t754_initPopup(recid);t754__updateLazyLoad(recid);t754__alignButtons_init(recid);t_onFuncLoad('t_store_addProductQuantityEvents',function(){t754_initProductQuantity(recid)});var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);document.body.dispatchEvent(event)},500)}
function t754_initProductQuantity(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var productList=rec.querySelectorAll('.t754__col, .t754__product-full');Array.prototype.forEach.call(productList,function(product){t_store_addProductQuantityEvents(product)})}
function t754__showMore(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var wrapperBlock=rec.querySelector('.t754');if(!wrapperBlock)return;var productColumns=wrapperBlock.querySelectorAll('.t754__col');var cardsSize=productColumns.length;var cardsCount=parseInt(wrapperBlock.getAttribute('data-show-count'),10);if(isNaN(cardsCount)||cardsCount<1)return;Array.prototype.forEach.call(productColumns,function(column){column.style.display='none'});for(var i=0;i<cardsCount;i++){if(productColumns[i]){productColumns[i].style.display='inline-block'}}
var showMoreButton=wrapperBlock.querySelector('.t754__showmore');if(!showMoreButton)return;if(showMoreButton.querySelector('td').textContent===''){showMoreButton.querySelector('td').textContent=t754__dict()}
if(cardsCount<productColumns.length){showMoreButton.style.display='inline-block'}
t754__showSeparator(wrapperBlock,cardsCount);showMoreButton.addEventListener('click',function(){var currentColumns=wrapperBlock.querySelectorAll('.t754__col');var currentColumnsShowed=0;Array.prototype.forEach.call(currentColumns,function(column){if(column.style.display==='inline-block'){++currentColumnsShowed}});for(var i=0;i<cardsCount+currentColumnsShowed;i++){if(currentColumns[i]){currentColumns[i].style.display='inline-block'}}
if(cardsCount+currentColumnsShowed>=cardsSize){showMoreButton.style.display='none'}
if(!document.querySelector('.t-records').getAttribute('data-tilda-mode')){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
t754__showSeparator(wrapperBlock,cardsCount+currentColumnsShowed);if(wrapperBlock.querySelector('[data-buttons-v-align]')){t754__alignButtons(recid)}})}
function t754__showSeparator(rec,cardsCount){if(window.jQuery&&rec instanceof jQuery){rec=rec.get(0)}
var allSeparators=rec.querySelectorAll('.t754__separator_number');Array.prototype.forEach.call(allSeparators,function(separator){separator.classList.add('t754__separator_hide');if(separator.getAttribute('data-product-separator-number')<=cardsCount){separator.classList.remove('t754__separator_hide')}})}
function t754__dict(){var dictionary={EN:'Load more',RU:'Загрузить ещё',FR:'Charger plus',DE:'Mehr laden',ES:'Carga más',PT:'Carregue mais',UK:'Завантажити ще',JA:'もっと読み込む',ZH:'裝載更多',};var language=window.browserLang;return dictionary[language]?dictionary[language]:dictionary.EN}
function t754__alignButtons_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;if(!rec.querySelector('[data-buttons-v-align]')){return}
try{t754__alignButtons(recid);if(document.querySelector('.t-records').getAttribute('data-tilda-mode')==='edit'){setInterval(function(){t754__alignButtons(recid)},200)}
window.addEventListener('resize',t_throttle(function(){if(window.noAdaptive&&window.isMobile){return}
t754__alignButtons(recid)},200));var wrapperBlock=rec.querySelector('.t754');if(wrapperBlock){wrapperBlock.addEventListener('displayChanged',function(){t754__alignButtons(recid)})}
if(window.isMobile){window.addEventListener('orientationchange',function(){t754__alignButtons(recid)})}}catch(error){console.log('buttons-v-align error: '+error.message)}}
function t754__alignButtons(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var wrappers=rec.querySelectorAll('.t754__textwrapper');var maxHeight=0;var container=rec.querySelector('.t754__parent');if(!container)return;var itemsInRow=parseInt(container.getAttribute('data-blocks-per-row'),10);if(!itemsInRow){itemsInRow=3}
var mobileView=window.innerWidth<=480;var tableView=window.innerWidth<=960&&window.innerWidth>480;var mobileOneRow=window.innerWidth<=960&&rec.querySelector('.t754__container_mobile-flex');var mobileTwoItemsInRow=window.innerWidth<=480&&rec.querySelector('.t754 .mobile-two-columns');if(mobileView){itemsInRow=1}
if(tableView){itemsInRow=2}
if(mobileTwoItemsInRow){itemsInRow=2}
if(mobileOneRow){itemsInRow=999999}
var count=1;var wrappersInRow=[];Array.prototype.forEach.call(wrappers,function(element){element.style.height='auto';if(itemsInRow===1){element.style.height='auto'}else{wrappersInRow.push(element);if(element.offsetHeight>maxHeight){maxHeight=element.offsetHeight}
Array.prototype.forEach.call(wrappersInRow,function(wrapper){wrapper.style.height=maxHeight+'px'});if(count===itemsInRow){count=0;maxHeight=0;wrappersInRow=[]}
count++}})}
function t754__hoverZoom_init(recid){if(window.isMobile)return;var rec=document.getElementById('rec'+recid);if(!rec)return;try{if(!rec.querySelector('[data-hover-zoom]')){return}
var hoverScript='https://static.tildacdn.com/js/tilda-hover-zoom-1.0.min.js';if(document.querySelector("script[src^='"+hoverScript+"']")){t_onFuncLoad('t_hoverZoom_init',function(){t_hoverZoom_init(recid)})}else{var script=document.createElement('script');script.type='text/javascript';script.src=hoverScript;script.onload=function(){setTimeout(function(){t_hoverZoom_init(recid)},500)};script.onerror=function(error){console.log('Upload script error: ',error)};document.head.appendChild(script)}}catch(error){console.log('Zoom image init error: '+error.message)}}
function t754__updateLazyLoad(recid){var scrollContainer=document.querySelector('#rec'+recid+' .t754__container_mobile-flex');var tRecords=document.querySelector('.t-records');if(!tRecords)return;var currentMode=tRecords.getAttribute('data-tilda-mode');if(scrollContainer&&currentMode!=='edit'&&currentMode!=='preview'){scrollContainer.addEventListener('scroll',t_throttle(function(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}))}}
function t754_initPopup(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var popup=rec.querySelector('.t-popup');var body=document.body;var popup=rec.querySelector('.t-popup');var linksProd=rec.querySelectorAll('[href^="#prodpopup"]');Array.prototype.forEach.call(linksProd,function(link){link.addEventListener('click',clickOnceHandler,!1);function clickOnceHandler(event){event.preventDefault();var product=link.closest('.js-product');var productLid=product.getAttribute('data-product-lid');t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid+' #t754__product-'+productLid)});link.removeEventListener('click',clickOnceHandler,!1)}
link.addEventListener('click',function(event){event.preventDefault();var isT1002Button=event.target.classList.contains('t1002__addBtn')||event.target.parentNode.classList.contains('t1002__addBtn');if(isT1002Button)return;t754_showPopup(recid);var product=link.closest('.js-product');var productLid=product.getAttribute('data-product-lid');var productFull=popup.querySelector('.js-product[data-product-lid="'+productLid+'"]');productFull.style.display='block';var analitics=link.getAttribute('data-track-popup');if(analitics&&productFull&&window.Tilda){var productName=productFull.querySelector('.js-product-name');if(productName){var virtTitle=productName.textContent;if(!virtTitle){virtTitle='prod'+productLid}
Tilda.sendEventToStatistics(analitics,virtTitle)}}
var currentUrl=window.location.href;if(currentUrl.indexOf('#!/tproduct/')<0&&currentUrl.indexOf('%23!/tproduct/')<0&&currentUrl.indexOf('#%21%2Ftproduct%2F')<0){if(history.replaceState){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+productLid)}}
t754_updateSlider(recid+' #t754__product-'+productLid);if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})});if(popup){popup.addEventListener('mousedown',function(event){var windowWidth=window.innerWidth;var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(event.clientX>windowWithoutScrollBar){return}
if(event.target===this){t754_closePopup(body,popup)}})}
var closeButtons=rec.querySelectorAll('.t-popup__close, .t754__close-text');Array.prototype.forEach.call(closeButtons,function(button){button.addEventListener('click',function(){t754_closePopup(body,popup)})});document.addEventListener('keydown',function(event){var isGalleryShowedOldLib=document.body.classList.contains('t-zoomer__show');if(isGalleryShowedOldLib)return;var isGalleryShowedNewLib=document.body.classList.contains('t-zoomer__active');if(isGalleryShowedNewLib)return;var isPopupShowed=document.body.classList.contains('t-body_popupshowed');if(!isPopupShowed)return;if(popup&&popup.classList.contains('t-popup_show')){if(event.keyCode===27){t754_closePopup(body,popup)}}});if(!document.getElementById('record'+recid)){t754_checkUrl(recid)}
t754_copyTypography(recid)}
function t754_showPopup(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var popup=rec.querySelector('.t-popup');var fullProducts=popup.querySelectorAll('.t754__product-full');Array.prototype.forEach.call(fullProducts,function(product){product.style.display='none'});popup.style.display='block';setTimeout(function(){popup.querySelector('.t-popup__container').classList.add('t-popup__container-animated');popup.classList.add('t-popup_show');if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},50);var body=document.body;body.classList.add('t-body_popupshowed');var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);body.dispatchEvent(event)}
function t754_closePopup(body,popup){var fullProducts=popup.querySelectorAll('.t754__product-full');body.classList.remove('t-body_popupshowed');popup.classList.remove('t-popup_show');var currentUrl=window.location.href;var indexToRemove=currentUrl.indexOf('#!/tproduct/');var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);body.dispatchEvent(event);if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=currentUrl.indexOf('%23!/tproduct/');if(indexToRemove<0){indexToRemove=currentUrl.indexOf('#%21%2Ftproduct%2F')}}
currentUrl=currentUrl.substring(0,indexToRemove);setTimeout(function(){popup.scrollTop=0;popup.style.display='none';Array.prototype.forEach.call(fullProducts,function(product){product.style.display='none'});if(history.replaceState){window.history.replaceState('','',currentUrl)}},300)}
function t754_updateSlider(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var slider=rec.querySelector('.t-slds__container');var paddingLeft=parseInt(slider.style.paddingLeft)||0;var paddingRight=parseInt(slider.style.paddingRight)||0;var sliderWrapper=rec.querySelector('.t-slds__items-wrapper');var sliderWidth=slider.clientWidth-(paddingLeft+paddingRight);var pos=parseFloat(sliderWrapper.getAttribute('data-slider-pos'));sliderWrapper.style.transform='translate3d(-'+sliderWidth*pos+'px, 0, 0)';t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
function t754_checkUrl(recid){var currentUrl=window.location.href;var tprodIndex=(currentUrl.indexOf('#!/tproduct/')+1||currentUrl.indexOf('%23!/tproduct/')+1||currentUrl.indexOf('#%21%2Ftproduct%2F')+1||currentUrl.indexOf('#!%2Ftproduct%2F')+1||currentUrl.indexOf('%23%21%2Ftproduct%2F')+1)-1;if(tprodIndex!==-1){var currentUrl=currentUrl.substring(tprodIndex,currentUrl.length);var curProdLid=currentUrl.substring(currentUrl.indexOf('-')+1,currentUrl.length);if(curProdLid){var curProdLidMatch=curProdLid.match(/([0-9]+)/g);if(curProdLidMatch){curProdLid=curProdLidMatch[0]}}
if(currentUrl.indexOf(recid)===-1)return;var rec=document.getElementById('rec'+recid);if(!rec)return;if(currentUrl.indexOf(recid)!==0&&rec.querySelector('[data-product-lid="'+curProdLid+'"]')){var currentLink=rec.querySelector('[data-product-lid="'+curProdLid+'"] [href^="#prodpopup"]');var event=document.createEvent('HTMLEvents');event.initEvent('click',!0,!1);if(currentLink){currentLink.dispatchEvent(event)}}}}
function t754_removeSizeStyles(styleStr){if(styleStr&&(styleStr.indexOf('font-size')!==-1||styleStr.indexOf('padding-top')!==-1||styleStr.indexOf('padding-bottom')!==-1)){var styleStrSplitted=styleStr.split(';');styleStr='';for(var i=0;i<styleStrSplitted.length;i++){if(styleStrSplitted[i].indexOf('font-size')!==-1||styleStrSplitted[i].indexOf('padding-top')!==-1||styleStrSplitted[i].indexOf('padding-bottom')!==-1){styleStrSplitted.splice(i,1);i--;continue}
if(!styleStrSplitted[i]){continue}
styleStr+=styleStrSplitted[i]+';'}}
return styleStr}
function t754_copyTypography(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var productTitle=rec.querySelector('.t754__title');var productDescription=rec.querySelector('.t754__descr');if(!productTitle||!productDescription){return}
var titleStyle=productTitle.getAttribute('style');var descrStyle=productDescription.getAttribute('style');var popupTitles=rec.querySelectorAll('.t-popup .t754__title');Array.prototype.forEach.call(popupTitles,function(title){title.setAttribute('style',t754_removeSizeStyles(titleStyle))});var popupDescription=rec.querySelectorAll('.t-popup .t754__descr, .t-popup .t754__text');Array.prototype.forEach.call(popupDescription,function(description){description.setAttribute('style',t754_removeSizeStyles(descrStyle))})}
if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.msMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.webkitMatchesSelector||Element.prototype.oMatchesSelector}
if(!Element.prototype.closest){Element.prototype.closest=function(s){var el=this;while(el&&el.nodeType===1){if(Element.prototype.matches.call(el,s)){return el}
el=el.parentElement||el.parentNode}
return null}}
function t347_setHeight(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var table=rec?rec.querySelector('.t347__table'):null;var tableWidth=table?table.offsetWidth:0;var tableHeight=tableWidth*0.5625;if(table)table.style.height=tableHeight+'px'}
function t347showvideo(recid){if(document.readyState!=='loading'){t347_createVideo(recid)}else{document.addEventListener('DOMContentLoaded',function(){t347_createVideo(recid)})}}
function t347_createVideo(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var videoContainer=rec.querySelector('.t347__video-container');var videoCarrier=rec.querySelector('.t347__video-carier');if(videoContainer)videoContainer.classList.remove('t347__hidden');if(!videoContainer.classList.contains('t347__html5video')&&!videoContainer.classList.contains('t347__vimeovideo')){var youTubeURL=videoContainer?videoContainer.getAttribute('data-content-popup-video-url-youtube'):'';var videoURL=youTubeURL?'https://www.youtube.com/embed/'+youTubeURL:'';videoCarrier.insertAdjacentHTML('beforeend','<iframe id="youtubeiframe'+recid+'" class="t347__iframe" width="100%" height="100%" src="'+videoURL+(videoURL.indexOf('?')!==-1?'&':'?')+'autoplay=1&rel=0" frameborder="0" allowfullscreen allow="autoplay"></iframe>')}
var videoWrapper=rec.querySelector('.t347__table');var computedHeight=window.getComputedStyle(videoWrapper).height;if(videoContainer.classList.contains('t347__html5video')){var videoSource=videoContainer.getAttribute('data-videomp4-url');if(!videoSource)return;videoCarrier.insertAdjacentHTML('beforeend','<video width="100%" autoplay controls>'+'<source src="'+videoSource+'" type="video/mp4">'+'Your browser does not support the video tag'+'</video>');var HTMLVideoHeight=videoCarrier.getAttribute('data-height');videoCarrier.height=HTMLVideoHeight?parseInt(HTMLVideoHeight,10):parseInt(computedHeight,10)}
if(videoContainer.classList.contains('t347__vimeovideo')){var videoSource=videoContainer.getAttribute('data-vimeo-url');var vimeoSourceHash=videoContainer.getAttribute('data-vimeo-hash');if(!videoSource)return;var vimeoCurrentSourse=vimeoSourceHash?videoSource+'?h='+vimeoSourceHash+'&autoplay=1':videoSource+'?autoplay=1';videoCarrier.insertAdjacentHTML('beforeend','<iframe '+'src="https://player.vimeo.com/video/'+vimeoCurrentSourse.trim()+'" '+'frameborder="0" '+'allow="autoplay; fullscreen; picture-in-picture" '+'allowfullscreen '+'style="width: 100%; height: 100%;"> '+'</iframe>');var vimeoVideoHeight=videoCarrier.getAttribute('data-height');videoCarrier.style.height=vimeoVideoHeight?vimeoVideoHeight:computedHeight}}
function t686_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t686');if(!container)return;setTimeout(function(){t686_setHeight(recId)},100);window.addEventListener('resize',t_throttle(function(){t686_setHeight(recId)}));container.addEventListener('displayChanged',function(){t686_setHeight(recId)})}
function t686_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t686');if(!container)return;var rows=rec.querySelectorAll('.t686__row');var col=rec.querySelector('.t686__col');var ratio=container.getAttribute('data-tile-ratio');if(!col)return;var colStyle=getComputedStyle(col,null);var colPaddingLeft=parseInt(colStyle.paddingLeft)||0;var colPaddingRight=parseInt(colStyle.paddingRight)||0;var colHeight=(col.clientWidth-(colPaddingLeft+colPaddingRight))*+ratio;var maxHeight=0;for(var i=0;i<rows.length;i++){var row=rows[i];var tables=row.querySelectorAll('.t686__table');for(var j=0;j<tables.length;j++){var table=tables[j];var textWrap=table.querySelector('.t686__textwrapper');var textWrapHeight=0;if(textWrap){textWrapHeight=textWrap.offsetHeight}
var cell=table.querySelector('.t686__cell');if(cell.classList.contains('t686__button-bottom')){var button=table.querySelector('.t686__button-container');if(button){textWrapHeight+=button.offsetHeight}}
if(textWrapHeight>maxHeight)maxHeight=textWrapHeight}
if(window.innerWidth>=960){if(maxHeight>colHeight){for(var j=0;j<tables.length;j++){var table=tables[j];table.style.height=maxHeight+'px';table.style.minHeight='auto'}}else{for(var j=0;j<tables.length;j++){var table=tables[j];table.style.height=colHeight+'px';table.style.minHeight='auto'}}}else{for(var j=0;j<tables.length;j++){var table=tables[j];table.style.height=null;table.style.minHeight=colHeight+'px'}}
if(!!document.documentMode){var bgs=row.querySelectorAll('.t686__bg');var overlays=row.querySelectorAll('.t686__overlay');var tableHeight=parseInt(row.querySelector('.t686__table').style.height);for(var j=0;j<bgs.length;j++){bgs[j].style.height=tableHeight+'px'}
for(var j=0;j<overlays.length;j++){overlays[j].style.height=tableHeight+'px'}}}}
function t270_scroll(hash,offset){if(!hash)return;t270_checkLoad(hash,offset);if(hash.indexOf('#!/tproduct/')!==-1||hash.indexOf('#!/tab/')!==-1){return!0}
var target;try{if(hash.substring(0,1)==='#'){target=document.getElementById(hash.substring(1))}else{target=document.querySelector(hash)}}catch(event){console.log('Exception t270: '+event.message);return!0}
if(!target){target=document.querySelector('a[name="'+hash.substr(1)+'"]');if(!target)return!0}
var isHistoryChangeAllowed=window.location.hash!==hash;var wrapperBlock=document.querySelector('.t270');var dontChangeHistory=wrapperBlock?Boolean(wrapperBlock.getAttribute('data-history-disabled')):!1;target=parseInt((target.getBoundingClientRect().top+window.pageYOffset)-offset,10);target=Math.abs(target);if('scrollBehavior' in document.documentElement.style){t_throttle(window.scrollTo({left:0,top:target,behavior:'smooth',}),500)}else{t270_scrollToEl(target)}
if(!dontChangeHistory&&isHistoryChangeAllowed){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
return!0}
function t270_checkLoad(hash,offset){if(window.t270_loadChecked)return;var sliderWrappers=document.body.querySelectorAll('.t-slds__items-wrapper');if(!sliderWrappers.length)return;var lastWrapper=sliderWrappers[sliderWrappers.length-1];var sliderImgs=lastWrapper?lastWrapper.querySelectorAll('.t-slds__bgimg'):[];var lastImg=sliderImgs[sliderImgs.length-1];var imageUrl=lastImg?window.getComputedStyle(lastImg).backgroundImage:'';imageUrl=imageUrl.substring(5,imageUrl.length-2);var preloaderImg=document.createElement('img');preloaderImg.src=imageUrl?imageUrl:'';preloaderImg.addEventListener('load',function(){t270_scroll(hash,offset);window.t270_loadChecked=!0})}
function t270_scrollToEl(target){var documentHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var bottomViewportPoint=documentHeight-document.documentElement.clientHeight;if(target>bottomViewportPoint)target=bottomViewportPoint;if(target===window.pageYOffset)return!1;var currentPosition=window.pageYOffset;var step=(target-currentPosition)/30;var difference=window.pageYOffset;var timerID=setInterval(function(){difference+=step;window.scrollTo(0,difference);document.body.setAttribute("data-scrollable","true");if((target-currentPosition<0&&window.pageYOffset<=target)||(target-currentPosition>0&&window.pageYOffset>=target)){clearInterval(timerID);document.body.removeAttribute("data-scrollable")}},10)}